name: prepare_cobalt_for_gens
description: Convert column mean in file .cobalt.ratio.pcf into GENS zoom-level data.
keywords:
  - cov
  - cobalt
  - tabix
  - bgzip
tools:
  - "python":
      description: "Converts COBALT coverage files into GENS zoom-level data."
      homepage: "https://www.python.org/"
      documentation: "https://docs.python.org/3/"
      tool_dev_url: "https://github.com/python/cpython"
      identifier: prepare_cobalt_for_gens
  - "bgzip":
      description: "Compress files using the BGZF format."
      homepage: "http://www.htslib.org/doc/bgzip.html"
      identifier: bgzip
  - "tabix":
      description: "Index tab-delimited genome position files."
      homepage: "http://www.htslib.org/doc/tabix.html"
      identifier: tabix
input:
  - meta:
      type: map
      description: |
        Groovy Map containing case information
        e.g. `[id: 'test', case_id: 'test', sample_id: 'subject_a', sample_type: 'tumor [or] normal', sex: 'female']`
  - cobalt_pcf:
      type: file
      description: COBALT PCF file, typically generated by COBALT.
      pattern: "*.cobalt.ratio.pcf"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing case information
        e.g. `[id: 'test', case_id: 'test', sample_id: 'subject_a', sample_type: 'tumor,normal', sex: 'female']`
  - bed:
      type: file
      description: bgzipped and tabix-indexed COBALT coverage zoom files
      pattern: "*.bed.gz"
  - tbi:
      type: file
      description: tabix index for COBALT coverage zoom files
      pattern: "*.bed.gz.tbi"
authors:
  - "@math.joh.bio"
  - "@kristinebilgrav"
