lint:
  actions_awsfulltest: false
  actions_awstest: false
  files_exist:
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .prettierignore
    - assets/sendmail_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
  multiqc_config: false
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Clinical Genomics Stockholm
  description: Customizable post-processing and extension layer for Oncoanalyser that adapts
    its outputs according to clinical and operational needs, adds missing analyses, and
    ensures flexibility for evolving standards while retaining Oncoanalyser's robust core.
  force: false
  is_nfcore: false
  name: oncorefiner
  org: Clinical-Genomics
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
