lint:
  actions_awsfulltest: False
  actions_awstest: False
  files_exist:
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/nf-core-oncorefiner_logo_light.png
    - docs/images/nf-core-oncorefiner_logo_light.png
    - docs/images/nf-core-oncorefiner_logo_dark.png
    - tests/.nftignore
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Clinical Genomics Stockholm
  description: Customizable post-processing and extension layer built on top of Oncoanalyser
    that adapts its outputs to clinical and operational needs, adds missing analyses,
    and ensures flexibility for evolving standards while retaining Oncoanalyser robust
    core
  force: false
  is_nfcore: false #change to false
  name: oncorefiner
  org: nf-core #change in future
  outdir: .
  version: 1.0.0dev
