name: "annotate_vcf_by_id"
description: Annotates VCF files by ID.
keywords:
  - python
  - annotate
  - genomics
tools:
  - "annotate_vcf_by_id":
      description: "Annotates VCF files by ID."
      identifier: annotate_vcf_by_id
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing case information
          e.g. `[id: case_id, case_id: case_id]`
    - vcf_file:
        type: file
        description: VCF file to be annotated
        pattern: "*.vcf"
    - tsv_file:
        type: file
        description: TSV file to use for annotation with the format ID\tTAG1\tTAG2\t...\tTAGN, header required.
        pattern: "*.tsv"
    - header_file:
        type: file
        description: VCF header file
        pattern: "*.txt"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing case information
            e.g. `[id: case_id, case_id: case_id]`
      - "*.vcf":
          type: file
          description: Annotated VCF file
          pattern: "*.vcf"
  - tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing case information
            e.g. `[id: case_id, case_id: case_id]`
      - "*.vcf.tbi":
          type: file
          description: Annotated VCF index file
          pattern: "*.vcf.tbi"
authors:
  - "@kristinebilgrav"
maintainers:
  - "@kristinebilgrav"
