name: prepare_amber_for_gens
description: Convert column mean in file *tumor.amber.baf.tsv.gz into GENS zoom-level data.
keywords:
  - baf
  - amber
  - tabix
  - bgzip
tools:
  - "prepare_amber_for_gens.py":
      description: "Converts AMBER BAF files into GENS zoom-level data."
      homepage: "https://www.python.org/"
      documentation: "https://docs.python.org/3/"
      tool_dev_url: "https://github.com/python/cpython"
      identifier: prepare_amber_for_gens
  - "bgzip":
      description: "Compress files using the BGZF format."
      homepage: "http://www.htslib.org/doc/bgzip.html"
      identifier: bgzip
  - "tabix":
      description: "Index tab-delimited genome position files."
      homepage: "http://www.htslib.org/doc/tabix.html"
      identifier: tabix
input:
  - meta:
      type: map
      description: |
        Groovy Map containing case information
        e.g. `[id: 'test', case_id: 'test', sample_id: 'subject_a', sample_type: 'tumor (or) normal', sex: 'female']`
  - amber_baf:
      type: file
      description: AMBER BAF file, typically generated by AMBER.
      pattern: "*.amber.baf.tsv.gz"
  - sampletype:
      type: string
      description: Sample type, e.g. "tumor_only" or "tumor_normal"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing case information
        e.g. `[id: 'test', case_id: 'test', sample_id: 'subject_a', sample_type: 'tumor,normal', sex: 'female']`
  - tumor_tsv:
      type: file
      description: bgzipped and tabix-indexed AMBER BAF TSV zoom file for tumor samples
      pattern: "*.baf.zoom.tsv.gz"
  - normal_tsv:
      type: file
      description: bgzipped and tabix-indexed AMBER BAF TSV zoom file for normal samples
      pattern: "*.baf.zoom.tsv.gz"
      optional: true
  - tumor_tbi:
      type: file
      description: tabix index for AMBER BAF TSV zoom file for tumor samples
      pattern: "*.baf.zoom.tsv.gz.tbi"
  - normal_tbi:
      type: file
      description: tabix index for AMBER BAF TSV zoom file for normal samples
      pattern: "*.baf.zoom.tsv.gz.tbi"
      optional: true
authors:
  - "@math.joh.bio"
  - "@kristinebilgrav"
