name: Add PR checklist_comment
on:
  pull_request:
    types:
      - opened

jobs:
  add_pr_checklist_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          #body-path: 'comment-template.md' to get comment body from a file at `.github/comment-template.md` 
          body: |
            ## PR checklist

            - [ ] This comment contains a description of changes (with reason).
            - [ ] If you've fixed a bug or added code that should be tested, add tests!
            - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/oncorefiner/tree/master/.github/CONTRIBUTING.md)
            - [ ] If necessary, also make a PR on the nf-core/oncorefiner _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
            - [ ] Make sure your code lints (`nf-core pipelines lint`).
            - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
            - [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
            - [ ] Usage Documentation in `docs/usage.md` is updated.
            - [ ] Output Documentation in `docs/output.md` is updated.
            - [ ] `CHANGELOG.md` is updated.
            - [ ] `README.md` is updated (including new tool citations and authors/contributors).
