name: Add PR checklist comment
on:
  pull_request:
    types:
      - opened

jobs:
  add_pr_checklist_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'pr_comment_template.md'
